### ISSUE TITLE
Will there be an equivalent to NaN?

### ISSUE THREAD

**Issue by johnhenry** [tc39/proposal-bigint#108]
Numbers in JavaScript use a concept of NaN (not a number) as defined by IEEE 754. Will there be an equivalent NaBN or BigNumber.NaN? Is this necessary?

**Comment by littledan** [comment]
The current specification does not have an equivalent of NaN. In situations that would give NaN for Number, BigInt throws an exception (may be a RangeError, SyntaxError or TypeError, depending on the case). How does this seem to you?

**Comment by johnhenry** [comment]
Seems like a good plan to me, though this was mostly an afterthought after considering https://github.com/tc39/proposal-bigint/issues/107. Frankly, I'm wondering about the usefulness of using NaN at all rather than throwing an error when we run into those situations with regular Numbers.

**Comment by littledan** [comment]
OK, I will leave the specification as is then.
