### ISSUE TITLE
ToBoolean semantics

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-bigint#11]
What should ToBoolean(`0n`) return, true or false?

Do people take advantage of `if (0)` going to the `else` branch that much? Do we need to extend this capability to new language features, or should we consider this something that we don't actually want to carry forward?

 I'll start with "false" following @BrendanEich's suggestion; for SIMD.js, we went with *true* for a zero vector.

**Comment by kgryte** [comment]
I do find `if ( falsey )` a common occurrence, including `if ( 0 )`.

I would prefer similar behavior to `if ( 0 )` for the proposed integer type. Hence, `ToBoolean( 0n )` should evaluate as `false`, while `ToBoolean( Xn )` should evaluate as `true` for all `X` not equal to `0`.

For reference, Julia casts its big integer type accordingly

```
julia> a = BigInt(1)
1

julia> bool(a)
true

julia> a = BigInt(0)
0

julia> bool(a)
false
```
and similarly for its integers (in `v0.4.x`)

```
julia> bool(0)
false

julia> bool(1)
true

**Comment by littledan** [comment]
Waldemar Horwat told me in an email,

> Regarding the ToBoolean issue:  ToBoolean(0n) should be false.  It should be true for any nonzero Integer.

This is what the current spec text says as well.

**Comment by littledan** [comment]
OK, we're sticking with the "logical" ToBoolean semantics described above.
