### ISSUE TITLE
"IsSafeInteger" and "NumberToBigInt" are unused

### ISSUE THREAD

**Issue by jakobkummerow** [tc39/proposal-bigint#110]
Unless I'm missing something, after merging #106, the internal functions "IsSafeInteger" (5.1.1) and "NumberToBigInt" (5.1.2) have no remaining uses (except each other). Looks like they can be removed from the proposal.

**Comment by littledan** [comment]
This looks like a bad typo--I didn't mean to remove the IsSafeInteger check from the BigInt constructor. I'll follow up with a patch today.
