### ISSUE TITLE
Shall we by the way replace the type of length, size and byteLength from 32-bit int to bigint?

### ISSUE THREAD

**Issue by dou4cc** [tc39/proposal-bigint#118]
like:
- `{Array|TypedArray}.prototype.length`
- `{ArrayBuffer|TypedArray}.prototype.byteLength`
- `{Set|Map|Blob}.prototype.size`

**Comment by littledan** [comment]
No, these are better off staying Numbers. Generally, the design of the BigInt proposal has been positing that everything which uses Number today, and everything which definitely fits in a Number, should continue using Number. For one, it would break existing users of these APIs to switch to BigInt.
