### ISSUE TITLE
Is `+a` more standardized than `Number(a)`?

### ISSUE THREAD

**Issue by dou4cc** [tc39/proposal-bigint#149]
According to the spec:
```javascript
Math.sign(0n); // TypeError

+0n; // TypeError

Number(0n); // 0
```

**Comment by dou4cc** [comment]
@ljharb What do you mean?

**Comment by ljharb** [comment]
Try those, do you see a similarity?

**Comment by ljharb** [comment]
The point is to avoid unintentional coercion.

However, specifically it does seem like Math.sign should be able to handle both BigInts and Numbers seamlessly - @littledan, what was the rationale there?

**Comment by dou4cc** [comment]
> what was the rationale there?

That's why I request a slide to explain https://github.com/tc39/proposal-bigint/commit/60f5143d69b14e36f1af422ec08050f0ad6a556b.

**Comment by dou4cc** [comment]
Following is type casting (coercion), isn't it?
![](https://user-images.githubusercontent.com/7764678/39625415-d8422228-4fcf-11e8-8ab1-c1a74274107e.png)
Why throw?

**Comment by ljharb** [comment]
RegExp implicitly converts to String, that’s what’s throwing.

**Comment by littledan** [comment]
@dou4cc I presented on these sorts of decisions in the May 2017 meeting. You can see the [slides](https://docs.google.com/presentation/d/1lrcjQzIFgdUXczeeAzs4GkTXJsRQU21UhtmXef70Qic/edit#slide=id.p} and the [notes](https://github.com/tc39/tc39-notes/blob/master/es8/2017-05/may-24.md#15iv-bigint-towards-stage-3) for more details.
