### ISSUE TITLE
Why does a string being compared with a bigInt know to convert itself into a bigInt rather than into a number?

### ISSUE THREAD

**Issue by dou4cc** [tc39/proposal-bigint#151]
...since there is not a `"bigint"` hint.

**Comment by bakkot** [comment]
Just answered this over in https://github.com/tc39/proposal-bigint/issues/150#issuecomment-387656192.

**Comment by bakkot** [comment]
The short answer is that it's specified to do so explicitly in the proposal's [Abstract Equality Comparison](https://tc39.github.io/proposal-bigint/#sec-abstract-equality-comparison) and [Abstract Relational Comparison](https://tc39.github.io/proposal-bigint/#sec-abstract-relational-comparison) spec text.

**Comment by dou4cc** [comment]
Since the implicit conversion here is logical, why forbid mix operands between string and bigInt?

**Comment by dou4cc** [comment]
And since mix operands between string and number are allowed instead, I of course think in math operands where implicit convertion is supported, string can be used as number. Does implicitly converting the string compared with a bigInt into a bigInt break?

**Comment by dou4cc** [comment]
Since you see the downside, do you also see that implicitly converting the string compared with a bigInt into a bigInt rather than into a number breaks things?

**Comment by dou4cc** [comment]
@ljharb Well, come here!

**Comment by ljharb** [comment]
@dou4cc I don't agree with you on this issue; if you want a Number from a string, you should explicitly convert it.
