### ISSUE TITLE
Should we have a Integer.prototype.toLocaleString method?

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-bigint#16]
I don't see a method within ICU for formatting arbitrary-precision numbers, but it seems like a natural thing to include in Integer. Thoughts?

**Comment by littledan** [comment]
cc @zbraniecki @jungshik @srl295

**Comment by zbraniecki** [comment]
I assume it would work analogously to `Number.prototype.toLocaleString`. If so, I would expect us to add it.

**Comment by littledan** [comment]
OK, I'll keep it. We'll probably need to make some upstream ICU changes to implement this, unfortunately.
