### ISSUE TITLE
Atomics.compareExchange update missing

### ISSUE THREAD

**Issue by jakobkummerow** [tc39/proposal-bigint#167]
Most of the Atomics operations ([Atomics.add](https://tc39.github.io/ecma262/#sec-atomics.add), Atomics.and, etc) use AtomicReadModifyWrite under the hood, which got an [update](https://tc39.github.io/proposal-bigint/#sec-atomicreadmodifywrite) to use ToBigInt instead of ToInteger for 64-bit operations.

[Atomics.compareExchange](https://tc39.github.io/ecma262/#sec-atomics.compareexchange), due to taking two value inputs (expectedValue, replacementValue), contains a modified copy of AtomicReadModifyWrite. The current proposal does not include any changes to Atomics.compareExchange, but it seems like the same change should be made there.

**Comment by littledan** [comment]
Good catch; we'll need a patch for this update. Thanks for filing this issue.
