### ISSUE TITLE
Add further TypedArray/DataView methods

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-bigint#17]
These are in the explainer but not in the draft spec text.

**Comment by kgryte** [comment]
Yes, the ability to create `Int64Array` and `Uint64Array` views from, e.g., `Float64Array` underlying buffers would be quite useful, particularly in allowing efficient floating-point bit manipulation for collections of doubles (or, from `Float32Array` underlying buffers, for complex `float32`).

**Comment by jaro-sevcik** [comment]
In addition to `(U)Int64Array`, how about exposing construction of BigInt from an arbitrary section of an array buffer, and similarly dumping the contents of BigInt to an array buffer?

**Comment by littledan** [comment]
@jaro-sevcik Interesting idea. A couple questions:
- This sounds a little more like a DataView type of operation than a TypedArray one, don't you think?
- I can picture unsigned semantics (given arguments for a byte start position and end, and endianness), but I'm not sure if you'd also want a signed version. Would you? Would it always sign-extend from the most significant bit, or is it more subtle?
- This operation seems like it would be possible to correctly implement in JS from other things, but a built-in one would be faster. Does that make it a good candidate for V2, after a minimal V1?

**Comment by littledan** [comment]
TypedArray and DataView methods are specified by https://github.com/littledan/proposal-integer/commit/abdef86ac340cc3c3afcb8a54cb29a707e0446b3 , but I'll leave this open to discuss further operations as @jaro-sevcik suggested.

**Comment by leobalter** [comment]
I'm fine both adding TypedArrays in this spec or in a follow up proposal.

**Comment by littledan** [comment]
OK, TypedArrays and DataViews have been spec'd; however, more advanced functions will be left for v2. The functions described in this thread could all be done in JavaScript, just more slowly.
