### ISSUE TITLE
Exact geometric computation

### ISSUE THREAD

**Issue by mikolalysenko** [tc39/proposal-bigint#19]
One application for big integers is exact geometric computation, as described here:

http://www.cgal.org/exact.html
http://cs.nyu.edu/exact/intro/

This is important in writing robust and correct geometric algorithms, since small floating point errors can often cause logical inconsistencies leading to catastrophic failures.  Here are some notes on this:

https://github.com/mikolalysenko/robust-arithmetic-notes

There are known techniques for exactly resolving geometric predicates on floating point numbers, however for geometric constructions (eg finding the intersection point of two line segments) it is necessary to use extended precision rational arithmetic.  Big integers can be extremely useful for this purpose as computations may be performed exactly internally by a library and then rounded only when the result is finally output.  An example using this approach can be found here:

https://github.com/mikolalysenko/overlay-pslg

If big integers became a standard feature in JavaScript then this system could potentially be made much faster.  The following features would be useful for performing exact rational computations:

* A fast GCD implementation
* A mechanism for rounding the quotient of two big integers to closest representable rational number
* A "sparse" or floating big integer data type allowing for a variable exponent
* A library function for rounding the square root/power of a big integer to the closest representable double

**Comment by mikolalysenko** [comment]
Some concrete applications that would benefit from exact geometric computations:

* GIS/mapping systems
* CAD software
* Video games
* Virtual reality

**Comment by littledan** [comment]
For a "sparse" big integer data type, do you think a generic big integer data type could intelligently choose when it should be sparse, or do we really need the user to select it?

For the other three library functions, do you think they will be better if put in the standard library than if implemented at the user level? If this is a performance thing, is it in terms of "we don't expect JS engines to optimize JS implementations well" or "there are processor instructions that you're missing out on by omitting these instructions"? The latter seems a bit more persuasive to me.

**Comment by littledan** [comment]
Thanks for the documentation about use cases for BigInts.
