### ISSUE TITLE
Clarify why +BigInt doesn't work

### ISSUE THREAD

**Issue by tjcrowder** [tc39/proposal-bigint#191]
In [ADVANCED.md](https://github.com/tc39/proposal-bigint/blob/master/ADVANCED.md) it says (under "Don't break asm.js"):

> Unary + followed by an expression is always either a Number, or results in throwing. For this reason, unfortunately, + on a BigInt needs to throw, rather than being symmetrical with + on Number: Otherwise, previously "type-declared" asm.js code would now be polymorphic.

The "for this reason" part there doesn't seem to follow. +BigInt can be defined to be a number, like +string is. That is, it can match the first option ("a Number") of "is always either a Number, or results in throwing" rather than the second ("results in throwing").

I'm sure there **is** a reason, but that paragraph doesn't seem to explain it.

**Comment by littledan** [comment]
Maybe we need to provide more background about asm.js here to make more sense.
