### ISSUE TITLE
Math.floor / ceil

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-bigint#197]
These seem to throw when given a BigInt; is there a reason they can’t return a BigInt in that case?

**Comment by daprahamian** [comment]
Do these functions have any meaning relative to BigInt? You can't really fllor or ceil an integer.

**Comment by ljharb** [comment]
Sure, they’d be identity obv, I’m just curious why an exception is better than a sensible value.

Number functions make sense to not be sensible with BigInt, but these are Math functions.

**Comment by daprahamian** [comment]
According to the spec, [Operations in the Math library will throw an error when used with BigInts](https://github.com/tc39/proposal-bigint/blob/master/README.md#other-exceptions).

**Comment by ljharb** [comment]
I see it’s intentional; I’m wondering more for a rationale - the justification for throwing behavior in this specific has typically been to avoid implicit coercion losing precision, which doesn’t apply to these, at least.

**Comment by jakobkummerow** [comment]
My guess is that the rationale is consistency. A bunch of the `Math.*` functions typically produce fractional values, so they return Numbers, so for consistency they also take Number inputs.

I assume that *if* there is consensus that "let those `Math` functions consume/produce BigInts where this doesn't break semantics" is a better rule to follow than "all `Math` functions consume/produce Numbers, period", then this would be fairly easy to change in a follow-up proposal. Personally, I'm inclined to think that simplicity is better.

(Examples: `Math.pow` could consume BigInts. If it does, then it should also return BigInts in those cases. Then what about mixed-type inputs? -- `Math.exp` could consume BigInts, but would always return a Number; in those cases where the input is outside safe Number range, the result would always be `Infinity`, so this wouldn't be a particularly interesting use case. -- `Math.round` could be no-op for BigInt inputs, but that too wouldn't be particularly interesting. -- How would you explain to people that `Math.pow(0n, 0n) === 1n` and `Math.round(0n) === 0n` but `Math.sin(0n) === 0.0`? What's `Math.max(1.0, 1n)`?

The current BigInt proposal does not aim to make BigInts and Numbers as interchangeable as possible. It clearly states/assumes that BigInts are a special type for special use cases. I think that's fair -- there's little value in having two ways to do exactly the same thing; having two ways to do things is useful when different things can be done with them.)

**Comment by littledan** [comment]
Right, the rationale is as @jakobkummerow explained. In general, the hope is to encourage people to be deliberate about whether they are using Number or BigInt--APIs are deliberately discouraged to "just work" between Number and BigInt, as sooner or later, this would lead to the risk of an accidental loss of precision for a BigInt.

**Comment by ljharb** [comment]
For Number methods that makes total sense; but “math” functions not working for integers, when they could easily do, seems troubling.

**Comment by littledan** [comment]
Well, I tried to explain at the previous TC39 meeting why I don't think parameters should be overloaded, but we didn't come to a strong conclusion. I will bring this topic back to the next meeting. I am not sure what you are getting at by "troubling", though; we will never satisfy all intuitions that people can come up with.

I could imagine overloading Math.min or Math.max, but Math.floor and Math.ceil just don't really have much meaning for integers.

**Comment by ljharb** [comment]
Oh, sure! I'm suggesting we do it on a case by case method - any Math method where it would have no relevant meaning for BigInts should of course throw, but all the ones where an integer makes sense would be nice to work.

Otherwise, we're going to end up with people wanting to add math-related functions to `BigInt`, and `Math` will really be `NumberMath` (or, we'll have a bunch of bigint-named functions on `Math`)- but I suppose that really depends on where we all land on overloading parameters. If you think we shouldn't, then I suppose that's the outcome you want - but if you think we should, then it's not. ¯\\\_(ツ)_/¯

**Comment by littledan** [comment]
I don't think there's a particular end to what people could want, but it's not clear that we can meet their expectations. Math, like the rest of JS and the Web platform, will remain Number-biased forever, since the alternative is loss of precision; this is our core design decision for BigInt. For this reason, I would like to keep the Math functions as they are.

**Comment by ljharb** [comment]
Some of the functions on it will, sure. But not all of them must. I'm not suggesting allowing anything that could lose precision.

**Comment by jakobkummerow** [comment]
> Otherwise, we're going to end up with people wanting to add math-related functions to `BigInt`, and `Math` will really be `NumberMath`

AFAIK the idea is to add further BigInt-related functionality in one or more follow-up proposals anyway; based on that outlook the simplicity of the mental model "`Math` is math with Numbers" (and, correspondingly, "`BigMathStrawman` is math with BigInts") seems appealing to me. What's wrong with having `BigInt.max(2n, 3n)`?

**Comment by ljharb** [comment]
Then I'd expect there to be a `Number.max`, or, instead, `BigIntMath.max`, or `Math.bigIntMax`. Math functions don't have a convention of going on constructors, they have a convention of going on `Math`.

**Comment by littledan** [comment]
Sounds like something we should work out within the `BigMathStrawman` proposal. This proposal tries to stay rather minimal, as the committee encouraged during its development.

**Comment by ljharb** [comment]
Seems answered for now; it can wait til that proposal, since we could always remove the exceptions in these methods in the future.
