### ISSUE TITLE
Is it possible to do operations on bigInts without using operators?

### ISSUE THREAD

**Issue by peterolson** [tc39/proposal-bigint#198]
I have a [library that works as a polyfill for BigInt](https://github.com/peterolson/BigInteger.js), but I am having an issue with exponentiation.

The library uses the native BigInt if it is available, but falls back on library functions for older JavaScript environments. I want to do something like this

```
var pow;
if(supportsNativeBigInt) {
  pow = function(a, b) { return a ** b };
} else {
  // fall back on library functions
}
```

The problem is that the `**` operator is not supported in older browsers, so this will cause a syntax error (even though the body of the if block will never be executed). This forces me to use eval:

```
if (supportsNativeBigInt) {
  // forced to use eval because ** is a syntax error on pre-ECMAScript2017 environments.
  pow = eval("(a,b)=>a**b");
}
```

Using `eval` for this makes me feel dirty, and it will [break on sites that have a content-security-policy preventing `eval`](https://github.com/peterolson/BigInteger.js/issues/172).

Is it possible to add class-level methods for BigInt operations (e.g. `BigInt.add`, `BigInt.pow`, etc?)? Is there any possible way to natively exponentiate BigInts without using the `**` operator?

**Comment by jakobkummerow** [comment]
As far as I'm aware there is no non-`**` way to do BigInt exponentiation. In [JSBI](https://github.com/GoogleChromeLabs/jsbi), for this reason we [decided](https://github.com/GoogleChromeLabs/jsbi/commit/426d4cc7e53b258b8e9551ca0ed7acaf827e3895) to leave the `supportsNativeBigInt` detection to transpilers like Babel. I agree that it would be nice if a library could do dynamic feature-detection, but to be fair I'm not sure how big the need for it is in practice.

I suppose if you want a workaround *now*, you could implement a special polyfill for doing exponentiation of native BigInts expressed in terms of multiplication. It's not very difficult, and would only be marginally less efficient than the [native implementation](https://chromium.googlesource.com/v8/v8/+/master/src/objects/bigint.cc#404), which you could use as inspiration.
