### ISSUE TITLE
Consider adding more functions to the standard library

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-bigint#20]
Should we have operations like popcount, find least/most significant bit set/unset? These could probably be implemented more efficiently as builtins using processor instructions than by the user. OTOH, maybe these are logically operations on memory (`ArrayBuffer`s? `Uint8Array`s?) than on BigInts; I'm not sure. This was a suggestion from Waldemar Horwat

**Comment by littledan** [comment]
@jfbastien Do you have any thoughts on operations that should exist? Or should this be left to WASM? Or v2 of the BigInt library?

**Comment by jfbastien** [comment]
It seems useful, but maybe v2? I think you should have the same capabilities on integers which JS has at a minimum. Other things as you mention seem nice to have. wasm [will have them in MVP](https://github.com/WebAssembly/design/blob/master/Semantics.md#32-bit-integer-operators) but only for `i32` and `i64`.

**Comment by littledan** [comment]
We'll leave more functions for v2.
