### ISSUE TITLE
Error on SetViewValue

### ISSUE THREAD

**Issue by caiolima** [tc39/proposal-bigint#200]
The new definition of `SetViewValue` (https://tc39.github.io/proposal-bigint/#sec-setviewvalue) is using `arrayTypeName` on line 5, however such variable is never initialized.
I think the right approach here would be:

```
...
5. If type is "BigUint64" or "BigInt64"...
...
```
Also, other operations like (`DataView.prototype.getBigInt64`, `DataView.prototype.getBigUint64`, etc) are using `Int64` or `Uint64`, while `SetValueInBuffer` expects `BigInt64` and `BigUint64`. I think we need to change those.

@littledan do you agree with those changes. I'm aplying them directly into ECMA262 BigInt patch.

**Comment by littledan** [comment]
Good catches. These changes sound good to me. Could you also make a PR against this proposal?
