### ISSUE TITLE
Right operands to Shift operations should be converted to Numeric shift amounts

### ISSUE THREAD

**Issue by msaboff** [tc39/proposal-bigint#38]
In section 1, the text for the three shift operations: leftShift, signedRightShift and un signedRightShift specify that the right operand is "converted from any type into a shift amount".  It seems to me that we should state that the right operand is "converted from any type into a **numeric** shift amount".  Since it is used in the updated bitwise operator text it makes sense.

**Comment by littledan** [comment]
This text is fixed up by https://github.com/tc39/proposal-bigint/commit/10063dc8efc7090430cab5630a86936087d15e2b .
