### ISSUE TITLE
Use T::unaryMinus() when specifying the semantics of the unary operator 

### ISSUE THREAD

**Issue by msaboff** [tc39/proposal-bigint#39]
The steps in 4.2.3.1 should use **T:unaryMinus(oldValue)** in step 6.

**Comment by littledan** [comment]
Seems like we need only one of {additiveZero, unaryMinus}. Any preference on which one we include? I'm inclined to go with unaryMinus, as @msaboff is suggesting.

**Comment by littledan** [comment]
FWIW Brendan's Int64 proposal, unaryMinus is used here, and zero (which I've renamed to additiveZero) is dead spec text. See https://raw.githubusercontent.com/BrendanEich/ecma262/int64/spec.html .
