### ISSUE TITLE
Handle NaN, Infinity properly in mixed comparison

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-bigint#50]
These are not mentioned explicitly, but comparing any BigInt with NaN should return false, Infinity should be treated specially, etc.

**Comment by Jack-Works** [comment]
Does BigInt has its' Infinity representation? It might be useful in some case (https://github.com/Jack-Works/proposal-Number.range/issues/8)

**Comment by littledan** [comment]
No, BigInt does not represent infinity. It only represents integers.
