### ISSUE TITLE
typeof?

### ISSUE THREAD

**Issue by alex-weej** [tc39/proposal-bigint#56]
I fear this may be a stupid question, but scanning the proposal I can't see what `typeof` is spec'd to return for this new primitive type.

**Comment by chicoxyzzy** [comment]
It is spec'd here: https://tc39.github.io/proposal-bigint/#sec-typeof-operator

**Comment by alex-weej** [comment]
Thanks, I searched the proposal for 'typeof' so it didn't find the link to the full spec! 😐
