### ISSUE TITLE
Minor issue in Number constructor

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/proposal-bigint#62]
```If Type(prim) is BigInt, let n be the Number value for prim.```

"the Number value" is not defined for 0.

**Comment by littledan** [comment]
Is it undefined? I see a definition here: https://tc39.github.io/ecma262/#sec-ecmascript-language-types-number-type . It seems like the Number value for 0 is +0.

**Comment by GeorgNeis** [comment]
Not sure what exactly in that text you're referring to. I see the first sentence: ```In this specification, the phrase “the Number value for x” where x represents an exact nonzero real mathematical quantity [...]```

**Comment by littledan** [comment]
@GeorgNeis Yes, that's the text I'm referring to. This paragraph explains how to round from a mathematical value to a Number. It seems to imply that "the Number value" for the mathematical 0 is +0, by my reading. Maybe other can help clarify. cc @waldemarhorwat @allenwb

**Comment by allenwb** [comment]
Actually, that paragraph explains how a _nonzero_ mathematical value is converted to a Number value.  As far as I can see, it doesn't explicitly define the meaning of  "Number value of 0" and if there is an implied definition the implication seems pretty weak.

I think this can be fixed simply by removing "nonzero" from the first sentence.  I don't think that qualification is necessary for the algorithm described in the rest of the paragraph.  In that case the "closest Number value" to mathematical 0 will be **+0**

**Comment by allenwb** [comment]
Of course fixing that paragraph doesn't really address @GeorgNeis original question.

Section 6.1.1 only defines "the Number value of X" for situations where X is a mathematical value so that doesn't apply to the situation in:

```
If Type(prim) is BigInt, let n be the Number value for prim.
```
Using current spec. language I think this would have to be stated as:
```
If Type(prim) is BigInt, let n be the Number value for the mathematical value of prim.
```
and "mathematical value of X" where X is a BitInt would have to be defined.

But I gather that @littledan has other ideas about how to deal with this.

**Comment by littledan** [comment]
Sorry, this was bad reading on my part--not sure how I repeatedly missed the word nonzero. I guess I'll put in an explicit statement that 0n goes to +0--sound good?

**Comment by allenwb** [comment]
I think that removing that "nonzero" would be sufficient  But, but sure, you can be more explicit about 0 mapping to +0 if you thing that will be helpful.

**Comment by littledan** [comment]
Do you know why nonzero is written there right now?

**Comment by allenwb** [comment]
Don't know.  It's been there since ES1.  Probably a bug.
