### ISSUE TITLE
Should Math.pow be updated to use Type(base)::exponentiate(base, exponent)?

### ISSUE THREAD

**Issue by rwaldron** [tc39/proposal-bigint#91]
Presently, [`Math.pow`](https://tc39.github.io/ecma262/#sec-math.pow) is defined as:

> Return the result of Applying the ** operator with base and exponent as specified in 12.6.4.

Which is what the last step of https://tc39.github.io/ecma262/#sec-exp-operator used to say prior to the changes this proposal introduces. Should this proposal also change Math.pow to the following: 

> If Type(base) does not equal Type(exponent), throw a TypeError exception.
> Return ? Type(base)::exponentiate(base, exponent).

**Comment by littledan** [comment]
Good catch; this specification is not intended to generalize Math.pow. I will apply the update you are suggesting.
