### ISSUE TITLE
[question] BigInt::bitwiseNOT(x)

### ISSUE THREAD

**Issue by caiolima** [tc39/proposal-bigint#99]
On Spec,  bitwiseNOT is defined to return ```-x-1``` [https://tc39.github.io/proposal-bigint/#sec-numeric-types-bigint-bitwiseNOT](https://tc39.github.io/proposal-bigint/#sec-numeric-types-bigint-bitwiseNOT) . In such case, if we have ```10n```, then ```~10n == -11n```?

**Comment by jakobkummerow** [comment]
Yes, just like `~10 === -11`.
